version: '3'
services:
  kazoo:
    container_name: kazoo
    hostname: kazoo.kazoo
    build:
      args:
        KAZOO_VERSION: 4.1.43
        KAZOO_CONFIGS_VERSION: 4.1.21
      context: images/kazoo
    image: telephoneorg/kazoo:${DOCKER_TAG:-latest}
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
      RABBITMQ_HOST: rabbitmq.kazoo
      COUCHDB_HOST: couchdb.kazoo
      KAZOO_LOG_LEVEL: info
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    tmpfs:
    - /tmp
    networks:
      kazoo:
        aliases:
        - kazoo.kazoo
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.kazoo
    image: telephoneorg/rabbitmq:latest
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
    tmpfs:
    - /var/lib/rabbitmq/mnesia
    networks:
      kazoo:
        aliases:
        - rabbitmq.kazoo
  couchdb:
    container_name: couchdb
    hostname: couchdb.kazoo
    image: telephoneorg/couchdb:latest
    environment:
      COUCHDB_DEV_INIT: 'true'
      ERLANG_COOKIE: change-me
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      COUCHDB_SHARDS: '1'
      COUCHDB_LOG_LEVEL: info
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      kazoo:
        aliases:
        - couchdb.kazoo
    volumes_from:
    - couchdb-data
  kzutil:
    build:
      args:
        KAZOO_VERSION: 4.1.43
      context: images/kzutil
    image: telephoneorg/kzutil:${DOCKER_TAG:-latest}
  couchdb-data:
    build: images/couchdb-data
    image: telephoneorg/couchdb-data:${DOCKER_TAG:-latest}
networks:
  kazoo:
